global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['demo-clickhouse-server:9363']
  - job_name: 'custom_clickhouse_metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
